### ISSUE TITLE
mlir-hs-tblgen broken

### ISSUE THREAD

**Issue by k355l3r-5yndr0m3** [google/mlir-hs#48]
## Expected Behavior
stack build terminate successfully.

## Actual Behavior
The binary mlir-hs-tblgen failed to compiled. Commenting out the line `#include "llvm/ADT/Optional.h"` in hs-generators.cc allows the compilation to be successful, but now mlir-hs-tblgen failed with `CommandLine Error: Option 'enable-fs-discriminator' registered more than once!`

## Steps to Reproduce the Problem

1.  Remove the line `#include "llvm/ADT/Optional.h"` from tblgen/hs-generators.cc
2.  Execute stack build 

## Specifications

- Version:  LLVM: 17.0.0git
- Platform: archlinux

**Comment by jpienaar** [comment]
Thanks for the report. Yes this one is pending updates.

**Comment by jpienaar** [comment]
Should be all fixed now.

**Comment by jpienaar** [comment]
@k355l3r-5yndr0m3 also feel free to reach out if you have any questions/want to share what you are working on. Github notifications are a bit wonky, but I'm easily reachable via email or on Discord (LLVM or IREE) or Discourse (LLVM).
