### ISSUE TITLE
Building On Windows?

### ISSUE THREAD

**Issue by MilesLitteral** [google/mlir-hs#50]
Hi, Ive been trying to build the project on Windows and made a lot of headway learning what would be necessary to build mlir-hs with minimal pain; I was curious if anyone had any insights or suggestions to limit any issues (like the fact building LLVM dylibs are currently unsupported on Windows.)

**Comment by jpienaar** [comment]
Unfortunately I haven't tried on Windows. We did have a different approach where we built a new library instead of trying to use upstream that could have worked here.

Would be useful to incorporate what you find though.

**Comment by MilesLitteral** [comment]
I wrote the following batch script (.bat) that you can run in the root mlir-hs directory to build LLVM/MLIR for windows. Presuming Ninja and cmake are installed and I don't mind opening a pull request to add this script for ease of use to the repo:
```batch
set root_dir=%cd%\llvm-project

if exist %root_dir% (
  echo "LLVM project dir found, continue"
) else (
  echo "LLVM Project dir not found, cloning and building"
  echo "Put the follwing on $PATH: %root_dir%"
  git clone https://github.com/llvm/llvm-project.git 
)

md %root_dir%\build 
cd %root_dir%\build 
call cmake %root_dir%\llvm -G "Ninja" -DCMAKE_INSTALL_PREFIX="%root_dir%\build\install" -DLLVM_ENABLE_PROJECTS=mlir -DLLVM_TARGETS_TO_BUILD="host" -DCMAKE_BUILD_TYPE=Release  -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_ENABLE_RTTI=ON -DLLVM_ENABLE_ZLIB=OFF -DLLVM_INSTALL_UTILS=ON -DLLVM_ENABLE_LIBEDIT=OFF 
call cmake --build . --config Release 
call cmake --build . --config Release --target install 
call cmake --build . --config Release --target check-mlir
```
I was then able to get mlir to build, put it on PATH, and function on windows. However I then encountered the following, very specific problem, with the mlir-hs library itself that would be more useful to touch on. 
--
My current problem is I can't get the mlir-hs library itself to build because in setup.hs when cabal attempts to use getLLVMConfig (specifically llvmConfigProgram to learn what version of llvm-config is available) the function fails with no output from llvm-config. Yet when you run the same command (`llvm-config --version`) in powershell it works just fine So I am now working through trying to get setup.hs to correctly capture llvm-config's output in windows.

**Comment by MilesLitteral** [comment]
I got further with building on Windows with a simplified approach. The manual steps I described is what I would now call "the hard way". You can leverage mingw directly to simplify installation (Works for any version before version 18, you have to build LLVM manually in MinGW to get later versions at time of writing): stack exec -- pacman -S mingw-w64-x86_64-mlir. However this leads to a different error, in which it can't find an llvm.lib and I'm currently unsure if any form of .dll could be linked. I intend to continue experimenting.

This is the error:
```
PS C:\Users\Me\OneDrive\Desktop\Projects\mlir-hs-main> stack build
mlir-hs> configure (lib)
C:/Users/Me/AppData/Local/Programs/stack/x86_64-windows/ghc-8.10.4/mingw/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lLLVM
collect2.exe: error: ld returned 1 exit status
```
